# Generated by Django 2.0.3 on 2019-01-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20190102_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_readed',
            new_name='is_read',
        ),
    ]
