# Generated by Django 2.0.3 on 2019-01-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='picture',
            new_name='comment',
        ),
    ]
