# Generated by Django 2.0.3 on 2019-01-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_auto_20190108_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.AddField(
            model_name='like',
            name='message',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tweet.Message'),
        ),
    ]
