# Generated by Django 2.0.3 on 2019-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_auto_20190108_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
