# Generated by Django 2.0.3 on 2019-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0012_auto_20190122_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='behance',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
